import { useState, useEffect, useCallback, useRef } from "react";
import { useParams, useNavigate } from "react-router-dom";
import { DashboardLayout } from "@/components/layout/DashboardLayout";
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
  CardDescription,
} from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Progress } from "@/components/ui/progress";
import { Badge } from "@/components/ui/badge";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Collapsible,
  CollapsibleContent,
  CollapsibleTrigger,
} from "@/components/ui/collapsible";
import {
  CheckCircle2,
  ChevronLeft,
  ChevronRight,
  Loader2,
  AlertCircle,
  BookOpen,
  Clock,
  FileText,
  Save,
  SkipForward,
  Plus,
  Sparkles,
  Tag,
  Users,
  Palette,
  ChevronDown,
  Pencil,
  X,
  Check,
} from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import {
  videoProcessingService,
  createSection,
  VideoProcessingJob,
  VideoChunk,
  PipelineDescription,
} from "@/services/videoProcessingService";
import api from "@/services/api";

// ── Local types ───────────────────────────────────────────────────────────────

interface Section {
  id: string;
  title: string;
}

// ── Sub-component: AI Insights panel ─────────────────────────────────────────
// Shows the pipeline description fields, all editable.

interface AiInsightsProps {
  description: PipelineDescription;
}

function AiInsightsPanel({ description }: AiInsightsProps) {
  const [open, setOpen] = useState(true);
  const [values, setValues] = useState({ ...description });
  const [tagInput, setTagInput] = useState("");

  const set = (field: keyof typeof values, val: string) =>
    setValues((p) => ({ ...p, [field]: val }));

  const addTag = () => {
    const t = tagInput.trim();
    if (!t || (values.seoTags as string[]).includes(t)) return;
    setValues((p) => ({ ...p, seoTags: [...(p.seoTags as string[]), t] }));
    setTagInput("");
  };

  const removeTag = (tag: string) =>
    setValues((p) => ({ ...p, seoTags: (p.seoTags as string[]).filter((t) => t !== tag) }));

  return (
    <Collapsible open={open} onOpenChange={setOpen}>
      <Card className="border-violet-200 bg-violet-50/60">
        <CardHeader className="pb-2">
          <CollapsibleTrigger asChild>
            <button className="flex w-full items-center justify-between text-left">
              <CardTitle className="text-base flex items-center gap-2 text-violet-800">
                <Sparkles className="h-4 w-4" />
                AI Course Insights
              </CardTitle>
              <ChevronDown
                className={`h-4 w-4 text-violet-600 transition-transform ${open ? "rotate-180" : ""}`}
              />
            </button>
          </CollapsibleTrigger>
          <CardDescription className="text-violet-600 text-xs">
            Generated by the AI pipeline from your video. All fields are editable — use them to
            fill in your course description, target audience, and SEO tags.
          </CardDescription>
        </CardHeader>

        <CollapsibleContent>
          <CardContent className="space-y-4 pt-0">
            {/* Summary */}
            <div className="space-y-1.5">
              <Label className="flex items-center gap-1.5 text-violet-700">
                <FileText className="h-3.5 w-3.5" />
                Course Summary
              </Label>
              <Textarea
                value={values.summary}
                onChange={(e) => set("summary", e.target.value)}
                rows={3}
                className="bg-white border-violet-200 text-sm resize-none"
                placeholder="AI-generated course summary…"
              />
            </div>

            <div className="grid sm:grid-cols-2 gap-4">
              {/* Target audience */}
              <div className="space-y-1.5">
                <Label className="flex items-center gap-1.5 text-violet-700">
                  <Users className="h-3.5 w-3.5" />
                  Target Audience
                </Label>
                <Input
                  value={values.targetAudience}
                  onChange={(e) => set("targetAudience", e.target.value)}
                  className="bg-white border-violet-200 text-sm"
                  placeholder="e.g. Beginner programmers aged 10–14"
                />
              </div>

              {/* Tone & style */}
              <div className="space-y-1.5">
                <Label className="flex items-center gap-1.5 text-violet-700">
                  <Palette className="h-3.5 w-3.5" />
                  Tone & Style
                </Label>
                <Input
                  value={values.toneAndStyle}
                  onChange={(e) => set("toneAndStyle", e.target.value)}
                  className="bg-white border-violet-200 text-sm"
                  placeholder="e.g. Friendly, visual, hands-on"
                />
              </div>
            </div>

            {/* SEO Tags */}
            <div className="space-y-1.5">
              <Label className="flex items-center gap-1.5 text-violet-700">
                <Tag className="h-3.5 w-3.5" />
                SEO Tags
              </Label>
              <div className="flex flex-wrap gap-1.5 mb-2">
                {(values.seoTags as string[]).map((tag) => (
                  <span
                    key={tag}
                    className="inline-flex items-center gap-1 bg-violet-100 text-violet-700 text-xs px-2 py-1 rounded-full"
                  >
                    {tag}
                    <button
                      onClick={() => removeTag(tag)}
                      className="hover:text-violet-900"
                    >
                      <X className="h-3 w-3" />
                    </button>
                  </span>
                ))}
                {(values.seoTags as string[]).length === 0 && (
                  <span className="text-xs text-violet-400 italic">No tags yet</span>
                )}
              </div>
              <div className="flex gap-2">
                <Input
                  value={tagInput}
                  onChange={(e) => setTagInput(e.target.value)}
                  onKeyDown={(e) => e.key === "Enter" && (e.preventDefault(), addTag())}
                  className="bg-white border-violet-200 text-sm flex-1"
                  placeholder="Type a tag and press Enter"
                />
                <Button
                  variant="outline"
                  size="sm"
                  onClick={addTag}
                  className="border-violet-200 text-violet-700"
                >
                  <Plus className="h-3.5 w-3.5" />
                </Button>
              </div>
            </div>
          </CardContent>
        </CollapsibleContent>
      </Card>
    </Collapsible>
  );
}

// ── Sub-component: Sections manager ──────────────────────────────────────────

interface SectionsPanelProps {
  courseId: string;
  sections: Section[];
  onSectionsChanged: (sections: Section[]) => void;
}

function SectionsPanel({ courseId, sections, onSectionsChanged }: SectionsPanelProps) {
  const { toast } = useToast();
  const [open, setOpen] = useState(true);
  const [newTitle, setNewTitle] = useState("");
  const [creating, setCreating] = useState(false);

  const handleCreate = async () => {
    const title = newTitle.trim();
    if (!title) return;
    setCreating(true);
    try {
      // POST /api/coursecreator/sections
      await createSection(courseId, title);

      // Re-fetch sections from the management endpoint so we get the real IDs
      const res = await api.get(`/coursecreator/courses/${courseId}/management`);
      const raw: { id: string; title: string }[] = res.data?.data?.sections ?? [];
      onSectionsChanged(raw.map((s) => ({ id: s.id, title: s.title })));

      setNewTitle("");
      toast({ title: `Section "${title}" created` });
    } catch {
      toast({ title: "Failed to create section", variant: "destructive" });
    } finally {
      setCreating(false);
    }
  };

  return (
    <Collapsible open={open} onOpenChange={setOpen}>
      <Card className="border-blue-200 bg-blue-50/50">
        <CardHeader className="pb-2">
          <CollapsibleTrigger asChild>
            <button className="flex w-full items-center justify-between text-left">
              <CardTitle className="text-base flex items-center gap-2 text-blue-800">
                <BookOpen className="h-4 w-4" />
                Course Sections
                <Badge variant="secondary" className="ml-1 bg-blue-100 text-blue-700 text-xs">
                  {sections.length}
                </Badge>
              </CardTitle>
              <ChevronDown
                className={`h-4 w-4 text-blue-600 transition-transform ${open ? "rotate-180" : ""}`}
              />
            </button>
          </CollapsibleTrigger>
          <CardDescription className="text-blue-600 text-xs">
            Create sections first, then map each video chunk to a section below.
          </CardDescription>
        </CardHeader>

        <CollapsibleContent>
          <CardContent className="pt-0 space-y-3">
            {/* Existing sections */}
            {sections.length > 0 && (
              <ul className="space-y-1.5">
                {sections.map((s, i) => (
                  <li
                    key={s.id}
                    className="flex items-center gap-2 text-sm bg-white border border-blue-100 rounded-lg px-3 py-2"
                  >
                    <span className="text-xs font-mono text-blue-400 w-5 shrink-0">
                      {i + 1}
                    </span>
                    <span className="flex-1 font-medium text-blue-900">{s.title}</span>
                    <Check className="h-3.5 w-3.5 text-blue-400 shrink-0" />
                  </li>
                ))}
              </ul>
            )}

            {sections.length === 0 && (
              <p className="text-sm text-blue-400 italic py-1">
                No sections yet — create one below.
              </p>
            )}

            {/* Create new */}
            <div className="flex gap-2">
              <Input
                value={newTitle}
                onChange={(e) => setNewTitle(e.target.value)}
                onKeyDown={(e) => e.key === "Enter" && !creating && handleCreate()}
                placeholder="New section title…"
                className="bg-white border-blue-200 text-sm flex-1"
                disabled={creating}
              />
              <Button
                size="sm"
                onClick={handleCreate}
                disabled={creating || !newTitle.trim()}
                className="shrink-0"
              >
                {creating ? (
                  <Loader2 className="h-3.5 w-3.5 animate-spin" />
                ) : (
                  <Plus className="h-3.5 w-3.5" />
                )}
                <span className="ml-1">Add</span>
              </Button>
            </div>
          </CardContent>
        </CollapsibleContent>
      </Card>
    </Collapsible>
  );
}

// ── Main page ─────────────────────────────────────────────────────────────────

export default function VideoReviewPage() {
  const { jobId } = useParams<{ jobId: string }>();
  const navigate  = useNavigate();
  const { toast } = useToast();

  // Job data
  const [job, setJob]             = useState<VideoProcessingJob | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [loadError, setLoadError] = useState<string | null>(null);

  // Step navigation
  const [currentStep, setCurrentStep] = useState(0);

  // Per-chunk editable state (keyed by chunkId)
  const [edits, setEdits] = useState<
    Record<string, { title: string; transcript: string }>
  >({});

  // Mapping: which section + lesson order per chunk
  const [mappings, setMappings] = useState<
    Record<string, { sectionId: string; order: number }>
  >({});

  // Sections (loaded from course, then updated as creator adds more)
  const [sections, setSections] = useState<Section[]>([]);

  // Per-chunk saving state
  const [saving, setSaving] = useState<Record<string, boolean>>({});

  // Track saved chunk IDs in a Set — updated synchronously so allSaved
  // flips to true in the same render cycle as the last save, without
  // depending on the async setJob state update.
  const [savedIds, setSavedIds] = useState<Set<string>>(new Set());

  // Auto-save debounce timers
  const autoSaveTimers = useRef<Record<string, ReturnType<typeof setTimeout>>>({});

  // ── Load job ────────────────────────────────────────────────────────────────

  useEffect(() => {
    if (!jobId) return;
    (async () => {
      try {
        const data = await videoProcessingService.getJob(jobId);
        setJob(data);

        // Seed savedIds from any chunks already marked saved (e.g. returning
        // to a partially-reviewed job).
        const alreadySaved = new Set(
          data.chunks.filter((c) => c.isSaved).map((c) => c.id)
        );
        setSavedIds(alreadySaved);

        // Initialise edits from chunk data
        const initEdits: Record<string, { title: string; transcript: string }> = {};
        data.chunks.forEach((c) => {
          initEdits[c.id] = { title: c.title, transcript: c.transcript };
        });
        setEdits(initEdits);
      } catch {
        setLoadError("Could not load the processing job.");
      } finally {
        setIsLoading(false);
      }
    })();
  }, [jobId]);

  // ── Load sections for the course ────────────────────────────────────────────

  useEffect(() => {
    if (!job?.courseId) return;
    api
      .get(`/coursecreator/courses/${job.courseId}/management`)
      .then((res) => {
        const raw: { id: string; title: string }[] = res.data?.data?.sections ?? [];
        setSections(raw.map((s) => ({ id: s.id, title: s.title })));
      })
      .catch(() => {
        // Silently fail — section creator panel still works
      });
  }, [job?.courseId]);

  // ── Auto-save chunk edits ────────────────────────────────────────────────────

  const scheduleAutoSave = useCallback(
    (chunkId: string, title: string, transcript: string) => {
      clearTimeout(autoSaveTimers.current[chunkId]);
      autoSaveTimers.current[chunkId] = setTimeout(async () => {
        try {
          await videoProcessingService.updateChunk(jobId!, chunkId, title, transcript);
        } catch {
          // Silent — will retry on next keystroke
        }
      }, 1200);
    },
    [jobId]
  );

  const handleEditChange = (
    chunkId: string,
    field: "title" | "transcript",
    value: string
  ) => {
    setEdits((prev) => {
      const next = { ...prev, [chunkId]: { ...prev[chunkId], [field]: value } };
      scheduleAutoSave(chunkId, next[chunkId].title, next[chunkId].transcript);
      return next;
    });
  };

  // ── Save chunk as lesson ─────────────────────────────────────────────────────

  const handleSaveChunk = async (chunk: VideoChunk) => {
    const mapping = mappings[chunk.id];
    if (!mapping?.sectionId) {
      toast({ title: "Choose a section first", variant: "destructive" });
      return;
    }

    setSaving((p) => ({ ...p, [chunk.id]: true }));
    try {
      await videoProcessingService.saveChunk(jobId!, chunk.id, {
        courseId:   job!.courseId,
        sectionId:  mapping.sectionId,
        title:      edits[chunk.id]?.title      ?? chunk.title,
        transcript: edits[chunk.id]?.transcript ?? chunk.transcript,
        order:      mapping.order,
      });

      // Mark saved in both local tracking Set (synchronous) and job state
      setSavedIds((prev) => new Set([...prev, chunk.id]));
      setJob((prev) =>
        prev
          ? {
              ...prev,
              chunks: prev.chunks.map((c) =>
                c.id === chunk.id ? { ...c, isSaved: true } : c
              ),
            }
          : prev
      );

      toast({ title: "Lesson created ✓" });

      // Auto-advance to next unsaved chunk.
      // Use job.chunks directly (not the stale `chunks` variable) and
      // exclude the chunk we just saved via the savedIds set.
      const allChunks = job?.chunks ?? [];
      const nextIdx = allChunks.findIndex(
        (c, i) => i > currentStep && !c.isSaved && c.id !== chunk.id
      );
      if (nextIdx !== -1) setCurrentStep(nextIdx);
    } catch {
      toast({ title: "Failed to save", variant: "destructive" });
    } finally {
      setSaving((p) => ({ ...p, [chunk.id]: false }));
    }
  };

  // ── Derived ──────────────────────────────────────────────────────────────────

  const chunks       = job?.chunks ?? [];
  const totalCount   = chunks.length;
  // Use savedIds (updated synchronously) so allSaved flips true immediately
  // on the last save, without waiting for setJob to re-render.
  const savedCount   = savedIds.size;
  const allSaved     = totalCount > 0 && savedCount >= totalCount;
  const currentChunk = chunks[currentStep] ?? null;

  // ── Loading / error guards ────────────────────────────────────────────────────

  if (isLoading) {
    return (
      <DashboardLayout>
        <div className="flex flex-col items-center justify-center min-h-[60vh] gap-3 text-muted-foreground">
          <Loader2 className="h-8 w-8 animate-spin text-primary" />
          <p>Loading video chunks…</p>
        </div>
      </DashboardLayout>
    );
  }

  if (loadError || !job) {
    return (
      <DashboardLayout>
        <div className="flex flex-col items-center justify-center min-h-[60vh] gap-3">
          <AlertCircle className="h-10 w-10 text-destructive" />
          <p className="text-muted-foreground">{loadError ?? "Job not found."}</p>
          <Button variant="outline" onClick={() => navigate(-1)}>Go Back</Button>
        </div>
      </DashboardLayout>
    );
  }

  if (job.status === "failed") {
    return (
      <DashboardLayout>
        <div className="flex flex-col items-center justify-center min-h-[60vh] gap-3">
          <AlertCircle className="h-10 w-10 text-destructive" />
          <p className="font-semibold">Processing failed</p>
          <p className="text-sm text-muted-foreground">{job.errorMessage}</p>
          <Button variant="outline" onClick={() => navigate(-1)}>Try Again</Button>
        </div>
      </DashboardLayout>
    );
  }

  // ── Render ────────────────────────────────────────────────────────────────────

  return (
    <DashboardLayout>
      <div className="mx-auto max-w-5xl space-y-5">

        {/* ── Header ── */}
        <div className="flex items-start justify-between">
          <div>
            <h1 className="text-2xl font-bold">Review Video Chunks</h1>
            <p className="text-muted-foreground text-sm mt-1">
              Create sections, review each AI-generated chunk, then save it as a lesson.
            </p>
          </div>
          {allSaved && (
            <Button onClick={() => navigate(`/creator/courses/${job.courseId}`)}>
              Back to Course
            </Button>
          )}
        </div>

        {/* ── Overall progress bar ── */}
        <Card>
          <CardContent className="pt-5 pb-4">
            <div className="flex items-center justify-between text-sm mb-2">
              <span className="font-medium">Chunks saved as lessons</span>
              <span className="text-muted-foreground">{savedCount} / {totalCount}</span>
            </div>
            <Progress
              value={(savedCount / Math.max(totalCount, 1)) * 100}
              className="h-2"
            />
          </CardContent>
        </Card>

        {/* ── AI Insights panel (pipeline description) ── */}
        {job.description && <AiInsightsPanel description={job.description} />}

        {/* ── Sections manager ── */}
        <SectionsPanel
          courseId={job.courseId}
          sections={sections}
          onSectionsChanged={setSections}
        />

        {/* ── Chunk review area ── */}
        <div className="grid grid-cols-[200px_1fr] gap-5">

          {/* Sidebar: chunk list */}
          <div className="space-y-1">
            <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wide px-1 mb-2">
              Chunks ({totalCount})
            </p>
            {chunks.map((chunk, i) => (
              <button
                key={chunk.id}
                onClick={() => setCurrentStep(i)}
                className={`w-full text-left rounded-lg px-3 py-2.5 text-sm transition-colors flex items-center gap-2 ${
                  i === currentStep
                    ? "bg-primary text-primary-foreground"
                    : "hover:bg-muted"
                }`}
              >
                <span className="shrink-0">
                  {savedIds.has(chunk.id) ? (
                    <CheckCircle2 className="h-4 w-4 text-green-400" />
                  ) : (
                    <div
                      className={`h-4 w-4 rounded-full border-2 ${
                        i === currentStep
                          ? "border-primary-foreground"
                          : "border-muted-foreground/40"
                      }`}
                    />
                  )}
                </span>
                <span className="truncate">
                  {edits[chunk.id]?.title || chunk.title || `Chunk ${i + 1}`}
                </span>
              </button>
            ))}
          </div>

          {/* Main panel: current chunk editor */}
          {currentChunk && (
            <div className="space-y-4 min-w-0">

              {/* Chunk meta row */}
              <div className="flex items-center gap-3 flex-wrap text-xs text-muted-foreground">
                <span className="flex items-center gap-1">
                  <Clock className="h-3.5 w-3.5" />
                  {currentChunk.startTime} → {currentChunk.endTime}
                </span>
                <span className="flex items-center gap-1">
                  <FileText className="h-3.5 w-3.5" />
                  Chunk {currentStep + 1} of {totalCount}
                </span>
                {savedIds.has(currentChunk.id) && (
                  <Badge variant="secondary" className="text-green-600 bg-green-50">
                    <CheckCircle2 className="h-3 w-3 mr-1" />
                    Saved as lesson
                  </Badge>
                )}
              </div>

              {/* AI Chunk Summary */}
              {currentChunk.summary && (
                <Card className="bg-amber-50/60 border-amber-200">
                  <CardContent className="pt-4 pb-3">
                    <p className="text-xs font-semibold text-amber-600 uppercase tracking-wide mb-1 flex items-center gap-1">
                      <Sparkles className="h-3.5 w-3.5" />
                      AI Chunk Summary
                    </p>
                    <p className="text-sm text-amber-900">{currentChunk.summary}</p>
                  </CardContent>
                </Card>
              )}

              {/* Editable lesson fields */}
              <Card>
                <CardHeader className="pb-3">
                  <CardTitle className="text-base flex items-center gap-2">
                    <Pencil className="h-4 w-4" />
                    Lesson Details
                  </CardTitle>
                  <CardDescription>
                    Edit the AI-generated title and transcript. Changes auto-save as you type.
                  </CardDescription>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div className="space-y-1.5">
                    <Label>Lesson Title</Label>
                    <Input
                      value={edits[currentChunk.id]?.title ?? ""}
                      onChange={(e) =>
                        handleEditChange(currentChunk.id, "title", e.target.value)
                      }
                      placeholder="e.g. Introduction to Variables"
                    />
                  </div>
                  <div className="space-y-1.5">
                    <Label>Transcript</Label>
                    <Textarea
                      value={edits[currentChunk.id]?.transcript ?? ""}
                      onChange={(e) =>
                        handleEditChange(currentChunk.id, "transcript", e.target.value)
                      }
                      rows={10}
                      className="font-mono text-sm resize-y"
                      placeholder="AI-generated transcript…"
                    />
                  </div>
                </CardContent>
              </Card>

              {/* Section mapping */}
              <Card>
                <CardHeader className="pb-3">
                  <CardTitle className="text-base flex items-center gap-2">
                    <BookOpen className="h-4 w-4" />
                    Map to Section
                  </CardTitle>
                  <CardDescription>
                    {sections.length === 0
                      ? "No sections yet — create one in the panel above first."
                      : "Choose which course section this chunk should become a lesson in."}
                  </CardDescription>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div className="space-y-1.5">
                    <Label>Section</Label>
                    {sections.length > 0 ? (
                      <Select
                        value={mappings[currentChunk.id]?.sectionId ?? ""}
                        onValueChange={(val) =>
                          setMappings((p) => ({
                            ...p,
                            [currentChunk.id]: {
                              sectionId: val,
                              order: p[currentChunk.id]?.order ?? currentStep + 1,
                            },
                          }))
                        }
                      >
                        <SelectTrigger>
                          <SelectValue placeholder="Choose a section" />
                        </SelectTrigger>
                        <SelectContent>
                          {sections.map((s) => (
                            <SelectItem key={s.id} value={s.id}>
                              {s.title}
                            </SelectItem>
                          ))}
                        </SelectContent>
                      </Select>
                    ) : (
                      <p className="text-sm text-muted-foreground border rounded-md px-3 py-2 bg-muted/40">
                        Create a section above to continue.
                      </p>
                    )}
                  </div>

                  <div className="space-y-1.5 max-w-[140px]">
                    <Label>Lesson Order</Label>
                    <Input
                      type="number"
                      min={1}
                      value={mappings[currentChunk.id]?.order ?? currentStep + 1}
                      onChange={(e) =>
                        setMappings((p) => ({
                          ...p,
                          [currentChunk.id]: {
                            sectionId: p[currentChunk.id]?.sectionId ?? "",
                            order: parseInt(e.target.value) || 1,
                          },
                        }))
                      }
                    />
                  </div>
                </CardContent>
              </Card>

              {/* Navigation + action row */}
              <div className="flex items-center justify-between pt-1 pb-4">
                <div className="flex gap-2">
                  <Button
                    variant="outline"
                    size="sm"
                    disabled={currentStep === 0}
                    onClick={() => setCurrentStep((i) => i - 1)}
                  >
                    <ChevronLeft className="h-4 w-4 mr-1" />
                    Previous
                  </Button>
                  <Button
                    variant="outline"
                    size="sm"
                    disabled={currentStep === totalCount - 1}
                    onClick={() => setCurrentStep((i) => i + 1)}
                  >
                    Next
                    <ChevronRight className="h-4 w-4 ml-1" />
                  </Button>
                </div>

                <div className="flex gap-2">
                  {!savedIds.has(currentChunk.id) && currentStep < totalCount - 1 && (
                    <Button
                      variant="ghost"
                      size="sm"
                      onClick={() => setCurrentStep((i) => i + 1)}
                    >
                      <SkipForward className="h-4 w-4 mr-1" />
                      Skip
                    </Button>
                  )}

                  <Button
                    size="sm"
                    disabled={
                      savedIds.has(currentChunk.id) ||
                      saving[currentChunk.id] ||
                      !mappings[currentChunk.id]?.sectionId
                    }
                    onClick={() => handleSaveChunk(currentChunk)}
                  >
                    {saving[currentChunk.id] ? (
                      <Loader2 className="h-4 w-4 animate-spin mr-1" />
                    ) : (
                      <Save className="h-4 w-4 mr-1" />
                    )}
                    {savedIds.has(currentChunk.id) ? "Saved" : "Save as Lesson"}
                  </Button>
                </div>
              </div>
            </div>
          )}
        </div>

        {/* ── Completion banner ── */}
        {allSaved && (
          <Card className="border-green-200 bg-green-50">
            <CardContent className="pt-5 flex items-center gap-4">
              <CheckCircle2 className="h-8 w-8 text-green-600 shrink-0" />
              <div>
                <p className="font-semibold text-green-800">All chunks saved as lessons!</p>
                <p className="text-sm text-green-700">
                  Head back to the course to publish it or add more content.
                </p>
              </div>
              <Button
                className="ml-auto"
                onClick={() => navigate(`/creator/courses/${job.courseId}`)}
              >
                Go to Course
              </Button>
            </CardContent>
          </Card>
        )}
      </div>
    </DashboardLayout>
  );
}